### ISSUE TITLE
Create awesome social list

### ISSUE THREAD

**Issue by serejandmyself** [citizen-cosmos/Awesome-Cosmos-Social#1]
- [x] Initial start
- [x] Feedback
- [x] Find help
- [x] Announce 1
- [x] Fill @johnniecosmos 
- [x] Announce 2 @johnniecosmos @serejandmyself

**Comment by ghost** [comment]
I have a pull request here

**Comment by ghost** [comment]
will be working on adding some stuff this week.

**Comment by ghost** [comment]
https://github.com/citizen-cosmos/Awesome-cosmos-social

Just linking for my reference :)

**Comment by ghost** [comment]
https://github.com/citizen-cosmos/Awesome-cosmos-social/pull/8/files
